### ISSUE TITLE
Converting NaturalJS macros into grammar files

### ISSUE THREAD

**Issue by jarble** [elshor/naturaljs#1]
I found a tool called [Nearley](https://github.com/kach/nearley) that could translate Naturaljs macros into grammar files, which could be used to generate parsers for Naturaljs.

A "macro" for NaturalJS could be translated into a Nearley grammar like this one:
```
# DEFINE length of Str AS return Str.length; END
macro ->  "length" ws "of' ws expr {% function(d) { var Str = d[3]; return $3+".length"; } %}
```
where `ws` represents whitespace.

To make this parser work, you would only need to combine this grammar rule with JavaScript's standard grammar.

**Comment by elshor** [comment]
Thanks for the suggestion. I was not aware of Nearley. I'll have a look at it
